import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from two_factor import TwoFactorAuth
from PIL.ImageQt import ImageQt


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(796, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(20, 20, 761, 531))
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageConnect = QtWidgets.QWidget()
        self.pageConnect.setObjectName("pageConnect")
        self.buttonConnServer = QtWidgets.QPushButton(self.pageConnect)
        self.buttonConnServer.setGeometry(QtCore.QRect(260, 220, 211, 91))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.buttonConnServer.setFont(font)
        self.buttonConnServer.setObjectName("buttonConnServer")
        self.stackedWidget.addWidget(self.pageConnect)
        self.pageAuth = QtWidgets.QWidget()
        self.pageAuth.setObjectName("pageAuth")
        self.authTabs = QtWidgets.QTabWidget(self.pageAuth)
        self.authTabs.setGeometry(QtCore.QRect(10, 10, 731, 501))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.authTabs.setFont(font)
        self.authTabs.setObjectName("authTabs")
        self.tabLogin = QtWidgets.QWidget()
        self.tabLogin.setObjectName("tabLogin")
        self.inputNickLog = QtWidgets.QLineEdit(self.tabLogin)
        self.inputNickLog.setGeometry(QtCore.QRect(310, 110, 241, 31))
        self.inputNickLog.setObjectName("inputNickLog")
        self.labelNickLog = QtWidgets.QLabel(self.tabLogin)
        self.labelNickLog.setGeometry(QtCore.QRect(170, 110, 91, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelNickLog.setFont(font)
        self.labelNickLog.setObjectName("labelNickLog")
        self.inputPassLog = QtWidgets.QLineEdit(self.tabLogin)
        self.inputPassLog.setGeometry(QtCore.QRect(310, 160, 241, 31))
        self.inputPassLog.setText("")
        self.inputPassLog.setEchoMode(QtWidgets.QLineEdit.Password)
        self.inputPassLog.setObjectName("inputPassLog")
        self.labelPassLog = QtWidgets.QLabel(self.tabLogin)
        self.labelPassLog.setGeometry(QtCore.QRect(170, 160, 81, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelPassLog.setFont(font)
        self.labelPassLog.setObjectName("labelPassLog")
        self.input2FALog = QtWidgets.QLineEdit(self.tabLogin)
        self.input2FALog.setGeometry(QtCore.QRect(310, 210, 241, 31))
        self.input2FALog.setText("")
        self.input2FALog.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input2FALog.setObjectName("input2FALog")
        self.label2FALog = QtWidgets.QLabel(self.tabLogin)
        self.label2FALog.setGeometry(QtCore.QRect(170, 210, 101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label2FALog.setFont(font)
        self.label2FALog.setObjectName("label2FALog")
        self.buttonLogin = QtWidgets.QPushButton(self.tabLogin)
        self.buttonLogin.setGeometry(QtCore.QRect(250, 260, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.buttonLogin.setFont(font)
        self.buttonLogin.setObjectName("buttonLogin")
        self.labelTitleLog = QtWidgets.QLabel(self.tabLogin)
        self.labelTitleLog.setGeometry(QtCore.QRect(320, 30, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.labelTitleLog.setFont(font)
        self.labelTitleLog.setObjectName("labelTitleLog")
        self.labelInstructLog = QtWidgets.QLabel(self.tabLogin)
        self.labelInstructLog.setGeometry(QtCore.QRect(240, 60, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labelInstructLog.setFont(font)
        self.labelInstructLog.setObjectName("labelInstructLog")
        self.commandPassReset = QtWidgets.QCommandLinkButton(self.tabLogin)
        self.commandPassReset.setGeometry(QtCore.QRect(280, 330, 171, 27))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        self.commandPassReset.setFont(font)
        self.commandPassReset.setObjectName("commandPassReset")
        self.authTabs.addTab(self.tabLogin, "")
        self.tabSignup = QtWidgets.QWidget()
        self.tabSignup.setObjectName("tabSignup")
        self.inputNickSign = QtWidgets.QLineEdit(self.tabSignup)
        self.inputNickSign.setGeometry(QtCore.QRect(220, 90, 231, 31))
        self.inputNickSign.setDragEnabled(True)
        self.inputNickSign.setPlaceholderText("")
        self.inputNickSign.setObjectName("inputNickSign")
        self.labelNickSign = QtWidgets.QLabel(self.tabSignup)
        self.labelNickSign.setGeometry(QtCore.QRect(70, 90, 91, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelNickSign.setFont(font)
        self.labelNickSign.setObjectName("labelNickSign")
        self.inputPassSign = QtWidgets.QLineEdit(self.tabSignup)
        self.inputPassSign.setGeometry(QtCore.QRect(220, 140, 231, 31))
        self.inputPassSign.setEchoMode(QtWidgets.QLineEdit.Password)
        self.inputPassSign.setObjectName("inputPassSign")
        self.labelPassSign = QtWidgets.QLabel(self.tabSignup)
        self.labelPassSign.setGeometry(QtCore.QRect(70, 140, 91, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelPassSign.setFont(font)
        self.labelPassSign.setObjectName("labelPassSign")
        self.labelQRCode = QtWidgets.QLabel(self.tabSignup)
        self.labelQRCode.setGeometry(QtCore.QRect(520, 120, 161, 161))
        self.labelQRCode.setText("")
        self.labelQRCode.setPixmap(QtGui.QPixmap("UI_files/../img/chat_icon.png"))
        self.labelQRCode.setScaledContents(True)
        self.labelQRCode.setObjectName("labelQRCode")
        self.inputPassConfSign = QtWidgets.QLineEdit(self.tabSignup)
        self.inputPassConfSign.setGeometry(QtCore.QRect(220, 190, 231, 31))
        self.inputPassConfSign.setText("")
        self.inputPassConfSign.setEchoMode(QtWidgets.QLineEdit.Password)
        self.inputPassConfSign.setObjectName("inputPassConfSign")
        self.labelPassConfSign = QtWidgets.QLabel(self.tabSignup)
        self.labelPassConfSign.setGeometry(QtCore.QRect(70, 190, 141, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelPassConfSign.setFont(font)
        self.labelPassConfSign.setObjectName("labelPassConfSign")
        self.buttonSign = QtWidgets.QPushButton(self.tabSignup)
        self.buttonSign.setGeometry(QtCore.QRect(210, 310, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.buttonSign.setFont(font)
        self.buttonSign.setObjectName("buttonSign")
        self.input2FASign = QtWidgets.QLineEdit(self.tabSignup)
        self.input2FASign.setGeometry(QtCore.QRect(220, 240, 231, 31))
        self.input2FASign.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input2FASign.setObjectName("input2FASign")
        self.label2FASign = QtWidgets.QLabel(self.tabSignup)
        self.label2FASign.setGeometry(QtCore.QRect(70, 240, 101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label2FASign.setFont(font)
        self.label2FASign.setObjectName("label2FASign")
        self.button2FAGen = QtWidgets.QPushButton(self.tabSignup)
        self.button2FAGen.setGeometry(QtCore.QRect(520, 320, 141, 31))
        self.button2FAGen.setObjectName("button2FAGen")
        self.labelTitleSign = QtWidgets.QLabel(self.tabSignup)
        self.labelTitleSign.setGeometry(QtCore.QRect(310, 10, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.labelTitleSign.setFont(font)
        self.labelTitleSign.setObjectName("labelTitleSign")
        self.labelQRCodeSign = QtWidgets.QLabel(self.tabSignup)
        self.labelQRCodeSign.setGeometry(QtCore.QRect(520, 40, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labelQRCodeSign.setFont(font)
        self.labelQRCodeSign.setWordWrap(True)
        self.labelQRCodeSign.setObjectName("labelQRCodeSign")
        self.labelInstructSign = QtWidgets.QLabel(self.tabSignup)
        self.labelInstructSign.setGeometry(QtCore.QRect(240, 40, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labelInstructSign.setFont(font)
        self.labelInstructSign.setObjectName("labelInstructSign")
        self.authTabs.addTab(self.tabSignup, "")
        self.tabResetPass = QtWidgets.QWidget()
        self.tabResetPass.setObjectName("tabResetPass")
        self.label2FAReset = QtWidgets.QLabel(self.tabResetPass)
        self.label2FAReset.setGeometry(QtCore.QRect(120, 160, 101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label2FAReset.setFont(font)
        self.label2FAReset.setObjectName("label2FAReset")
        self.labelPassConfReset = QtWidgets.QLabel(self.tabResetPass)
        self.labelPassConfReset.setGeometry(QtCore.QRect(120, 210, 171, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelPassConfReset.setFont(font)
        self.labelPassConfReset.setObjectName("labelPassConfReset")
        self.input2FAReset = QtWidgets.QLineEdit(self.tabResetPass)
        self.input2FAReset.setGeometry(QtCore.QRect(320, 160, 231, 31))
        self.input2FAReset.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input2FAReset.setObjectName("input2FAReset")
        self.inputPassConfReset = QtWidgets.QLineEdit(self.tabResetPass)
        self.inputPassConfReset.setGeometry(QtCore.QRect(320, 210, 231, 31))
        self.inputPassConfReset.setText("")
        self.inputPassConfReset.setEchoMode(QtWidgets.QLineEdit.Password)
        self.inputPassConfReset.setObjectName("inputPassConfReset")
        self.inputPassReset = QtWidgets.QLineEdit(self.tabResetPass)
        self.inputPassReset.setGeometry(QtCore.QRect(320, 260, 231, 31))
        self.inputPassReset.setEchoMode(QtWidgets.QLineEdit.Password)
        self.inputPassReset.setObjectName("inputPassReset")
        self.labelPassReset = QtWidgets.QLabel(self.tabResetPass)
        self.labelPassReset.setGeometry(QtCore.QRect(120, 260, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelPassReset.setFont(font)
        self.labelPassReset.setObjectName("labelPassReset")
        self.labelNickReset = QtWidgets.QLabel(self.tabResetPass)
        self.labelNickReset.setGeometry(QtCore.QRect(120, 100, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelNickReset.setFont(font)
        self.labelNickReset.setObjectName("labelNickReset")
        self.inputNickReset = QtWidgets.QLineEdit(self.tabResetPass)
        self.inputNickReset.setGeometry(QtCore.QRect(320, 100, 231, 31))
        self.inputNickReset.setText("")
        self.inputNickReset.setDragEnabled(True)
        self.inputNickReset.setObjectName("inputNickReset")
        self.labelTitleReset = QtWidgets.QLabel(self.tabResetPass)
        self.labelTitleReset.setGeometry(QtCore.QRect(240, 20, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.labelTitleReset.setFont(font)
        self.labelTitleReset.setObjectName("labelTitleReset")
        self.labelInstructReset = QtWidgets.QLabel(self.tabResetPass)
        self.labelInstructReset.setGeometry(QtCore.QRect(220, 60, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labelInstructReset.setFont(font)
        self.labelInstructReset.setObjectName("labelInstructReset")
        self.buttonReset = QtWidgets.QPushButton(self.tabResetPass)
        self.buttonReset.setGeometry(QtCore.QRect(250, 320, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.buttonReset.setFont(font)
        self.buttonReset.setObjectName("buttonReset")
        self.authTabs.addTab(self.tabResetPass, "")
        self.stackedWidget.addWidget(self.pageAuth)
        self.pageChatActive = QtWidgets.QWidget()
        self.pageChatActive.setObjectName("pageChatActive")
        self.buttonMessageSendActive = QtWidgets.QPushButton(self.pageChatActive)
        self.buttonMessageSendActive.setGeometry(QtCore.QRect(50, 500, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.buttonMessageSendActive.setFont(font)
        self.buttonMessageSendActive.setAutoDefault(True)
        self.buttonMessageSendActive.setFlat(False)
        self.buttonMessageSendActive.setObjectName("buttonMessageSendActive")
        self.inputMessageActive = QtWidgets.QTextEdit(self.pageChatActive)
        self.inputMessageActive.setGeometry(QtCore.QRect(20, 420, 721, 61))
        self.inputMessageActive.setObjectName("inputMessageActive")
        self.displayMessageActive = QtWidgets.QTextEdit(self.pageChatActive)
        self.displayMessageActive.setGeometry(QtCore.QRect(20, 40, 721, 361))
        self.displayMessageActive.setReadOnly(True)
        self.displayMessageActive.setObjectName("displayMessageActive")
        self.comboRecipientActive = QtWidgets.QComboBox(self.pageChatActive)
        self.comboRecipientActive.setGeometry(QtCore.QRect(590, 500, 131, 31))
        self.comboRecipientActive.setObjectName("comboRecipientActive")
        self.comboRecipientActive.addItem("")
        self.comboRecipientActive.addItem("")
        self.comboRecipientActive.addItem("")
        self.comboRecipientActive.addItem("")
        self.labelSendToActive = QtWidgets.QLabel(self.pageChatActive)
        self.labelSendToActive.setGeometry(QtCore.QRect(510, 500, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.labelSendToActive.setFont(font)
        self.labelSendToActive.setObjectName("labelSendToActive")
        self.buttonGoToArchive = QtWidgets.QPushButton(self.pageChatActive)
        self.buttonGoToArchive.setGeometry(QtCore.QRect(590, 0, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.buttonGoToArchive.setFont(font)
        self.buttonGoToArchive.setAutoDefault(True)
        self.buttonGoToArchive.setFlat(False)
        self.buttonGoToArchive.setObjectName("buttonGoToArchive")
        self.stackedWidget.addWidget(self.pageChatActive)
        self.pageChatArchive = QtWidgets.QWidget()
        self.pageChatArchive.setObjectName("pageChatArchive")
        self.displayMessageArchive = QtWidgets.QTextEdit(self.pageChatArchive)
        self.displayMessageArchive.setGeometry(QtCore.QRect(20, 80, 721, 441))
        self.displayMessageArchive.setReadOnly(True)
        self.displayMessageArchive.setObjectName("displayMessageArchive")
        self.labelTitleArchive = QtWidgets.QLabel(self.pageChatArchive)
        self.labelTitleArchive.setGeometry(QtCore.QRect(260, 40, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.labelTitleArchive.setFont(font)
        self.labelTitleArchive.setObjectName("labelTitleArchive")
        self.buttonDeleteHistory = QtWidgets.QPushButton(self.pageChatArchive)
        self.buttonDeleteHistory.setGeometry(QtCore.QRect(620, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.buttonDeleteHistory.setFont(font)
        self.buttonDeleteHistory.setAutoDefault(True)
        self.buttonDeleteHistory.setFlat(False)
        self.buttonDeleteHistory.setObjectName("buttonDeleteHistory")
        self.buttonGoToActiveChat = QtWidgets.QPushButton(self.pageChatArchive)
        self.buttonGoToActiveChat.setGeometry(QtCore.QRect(30, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.buttonGoToActiveChat.setFont(font)
        self.buttonGoToActiveChat.setAutoDefault(True)
        self.buttonGoToActiveChat.setFlat(False)
        self.buttonGoToActiveChat.setObjectName("buttonGoToActiveChat")
        self.stackedWidget.addWidget(self.pageChatArchive)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 796, 24))
        self.menubar.setObjectName("menubar")
        self.menuFIle = QtWidgets.QMenu(self.menubar)
        self.menuFIle.setObjectName("menuFIle")
        self.menuActions = QtWidgets.QMenu(self.menubar)
        self.menuActions.setObjectName("menuActions")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionCut = QtWidgets.QAction(MainWindow)
        self.actionCut.setObjectName("actionCut")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionRefresh = QtWidgets.QAction(MainWindow)
        self.actionRefresh.setObjectName("actionRefresh")
        self.actionQuit_2 = QtWidgets.QAction(MainWindow)
        self.actionQuit_2.setObjectName("actionQuit_2")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionArchives = QtWidgets.QAction(MainWindow)
        self.actionArchives.setObjectName("actionArchives")
        self.menuFIle.addAction(self.actionRefresh)
        self.menuFIle.addAction(self.actionClose)
        self.menuActions.addAction(self.actionCopy)
        self.menuActions.addAction(self.actionCut)
        self.menuActions.addAction(self.actionPaste)
        self.menubar.addAction(self.menuFIle.menuAction())
        self.menubar.addAction(self.menuActions.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.authTabs.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.buttonConnServer.clicked.connect(self.connect_server)
        self.button2FAGen.clicked.connect(self.generate_qrcode)
        self.buttonLogin.clicked.connect(self.login)
        self.buttonMessageSendActive.clicked.connect(self.send_message)
        self.commandPassReset.clicked.connect(self.switch_reset)
        self.buttonGoToArchive.clicked.connect(self.go_to_archive)
        self.buttonGoToActiveChat.clicked.connect(self.go_to_active_chat)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.buttonConnServer.setText(_translate("MainWindow", "CONNECT"))
        self.inputNickLog.setPlaceholderText(
            _translate("MainWindow", "Enter your Nickname")
        )
        self.labelNickLog.setText(_translate("MainWindow", "Nickname"))
        self.inputPassLog.setPlaceholderText(
            _translate("MainWindow", "Enter your password")
        )
        self.labelPassLog.setText(_translate("MainWindow", "Password"))
        self.input2FALog.setPlaceholderText(
            _translate("MainWindow", "Enter your 6 digit 2FA Code")
        )
        self.label2FALog.setText(_translate("MainWindow", "2FA Code"))
        self.buttonLogin.setText(_translate("MainWindow", "LOG IN"))
        self.labelTitleLog.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center">LOG IN</p></body></html>',
            )
        )
        self.labelInstructLog.setText(
            _translate(
                "MainWindow", "Fill in all the fields below using your credentials"
            )
        )
        self.commandPassReset.setText(_translate("MainWindow", "Forgot your password?"))
        self.authTabs.setTabText(
            self.authTabs.indexOf(self.tabLogin), _translate("MainWindow", "Login")
        )
        self.inputNickSign.setToolTip(
            _translate("MainWindow", "Nickname must be at least 6 characters long")
        )
        self.labelNickSign.setText(_translate("MainWindow", "Nickname"))
        self.inputPassSign.setToolTip(
            _translate(
                "MainWindow",
                "The password must be at least 8 character long, and include at least one undercase letter, one lowercase letter, one character and one special character",
            )
        )
        self.labelPassSign.setText(_translate("MainWindow", "Password"))
        self.inputPassConfSign.setToolTip(
            _translate(
                "MainWindow", "The confirm passsword fieldmust match the password field"
            )
        )
        self.labelPassConfSign.setText(_translate("MainWindow", "Confirm Password"))
        self.buttonSign.setText(_translate("MainWindow", "SIGN UP"))
        self.input2FASign.setToolTip(
            _translate(
                "MainWindow",
                "Enter the 6 digit code geenrated by the authenticator app",
            )
        )
        self.label2FASign.setText(_translate("MainWindow", "2FA Code"))
        self.button2FAGen.setToolTip(_translate("MainWindow", "Generate A New QRCode"))
        self.button2FAGen.setText(_translate("MainWindow", "Generate QRCode"))
        self.labelTitleSign.setText(_translate("MainWindow", "SIGN UP"))
        self.labelQRCodeSign.setText(
            _translate(
                "MainWindow",
                "Generate the QRCode After Entering Your Nickname and Scan it using an Authenticator App to Set Up 2FA",
            )
        )
        self.labelInstructSign.setText(
            _translate("MainWindow", "Fill in all the fields below as required")
        )
        self.authTabs.setTabText(
            self.authTabs.indexOf(self.tabSignup), _translate("MainWindow", "Signup")
        )
        self.label2FAReset.setText(_translate("MainWindow", "2FA Code"))
        self.labelPassConfReset.setText(
            _translate("MainWindow", "Confirm New Password")
        )
        self.input2FAReset.setToolTip(
            _translate(
                "MainWindow",
                "Enter the 6 digit code geenrated by the authenticator app",
            )
        )
        self.input2FAReset.setPlaceholderText(
            _translate("MainWindow", "Enter 6 digit Authenticator Code")
        )
        self.inputPassConfReset.setToolTip(
            _translate(
                "MainWindow",
                "The confirm new passsword fieldmust match the new password field",
            )
        )
        self.inputPassConfReset.setPlaceholderText(
            _translate("MainWindow", "Confirm Your New Password")
        )
        self.inputPassReset.setToolTip(
            _translate(
                "MainWindow",
                "The new password must be at least 8 character long, and include at least one undercase letter, one lowercase letter, one character and one special character.",
            )
        )
        self.inputPassReset.setPlaceholderText(
            _translate("MainWindow", "Enter Your New Password")
        )
        self.labelPassReset.setText(_translate("MainWindow", "New Password"))
        self.labelNickReset.setText(_translate("MainWindow", "Nickname"))
        self.inputNickReset.setToolTip(_translate("MainWindow", "Enter your nickname"))
        self.inputNickReset.setPlaceholderText(
            _translate("MainWindow", "Enter Your Nickname")
        )
        self.labelTitleReset.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center">RESET PASSWORD</p></body></html>',
            )
        )
        self.labelInstructReset.setText(
            _translate(
                "MainWindow", "Fill in all the fields below to reset your password"
            )
        )
        self.buttonReset.setText(_translate("MainWindow", "RESET PASSWORD"))
        self.authTabs.setTabText(
            self.authTabs.indexOf(self.tabResetPass),
            _translate("MainWindow", "Reset Password"),
        )
        self.buttonMessageSendActive.setText(_translate("MainWindow", "SEND"))
        self.comboRecipientActive.setItemText(0, _translate("MainWindow", "Everyone"))
        self.comboRecipientActive.setItemText(1, _translate("MainWindow", "First User"))
        self.comboRecipientActive.setItemText(
            2, _translate("MainWindow", "Second User")
        )
        self.comboRecipientActive.setItemText(3, _translate("MainWindow", "Third Year"))
        self.labelSendToActive.setText(_translate("MainWindow", "Send To:"))
        self.buttonGoToArchive.setText(_translate("MainWindow", "Archived Messages"))
        self.labelTitleArchive.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center">ARCHIVED MESSAGES</p></body></html>',
            )
        )
        self.buttonDeleteHistory.setText(_translate("MainWindow", "Delete History"))
        self.buttonGoToActiveChat.setText(_translate("MainWindow", "Back to Chat"))
        self.menuFIle.setTitle(_translate("MainWindow", "FIle"))
        self.menuActions.setTitle(_translate("MainWindow", "Actions"))
        self.actionQuit.setText(_translate("MainWindow", "Refresh"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionCopy.setStatusTip(_translate("MainWindow", "Copy Text"))
        self.actionCopy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionCut.setText(_translate("MainWindow", "Cut"))
        self.actionCut.setStatusTip(_translate("MainWindow", "Move Text"))
        self.actionCut.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.actionPaste.setStatusTip(_translate("MainWindow", "Paste Text"))
        self.actionPaste.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.actionRefresh.setText(_translate("MainWindow", "Refresh"))
        self.actionRefresh.setStatusTip(
            _translate("MainWindow", "Refresh your Connection")
        )
        self.actionRefresh.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionQuit_2.setText(_translate("MainWindow", "Quit"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionClose.setStatusTip(_translate("MainWindow", "Close the Application"))
        self.actionClose.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionArchives.setText(_translate("MainWindow", "Archives"))
        self.actionArchives.setStatusTip(_translate("MainWindow", "View Archives"))

    def connect_server(self):
        self.stackedWidget.setCurrentIndex(1)

    def generate_qrcode(self):
        # Generate QR code image for two factor authentication
        self.two_factor_auth = TwoFactorAuth()
        img = self.two_factor_auth.generate(self.inputNickSign.text())
        image = ImageQt(img.convert("RGBA"))
        self.secret_key = self.two_factor_auth.secret_key
        self.labelQRCode.setPixmap(QtGui.QPixmap.fromImage(image))

    def login(self):
        self.stackedWidget.setCurrentIndex(2)

    def send_message(self):
        # set recipient to currently selected
        recipient = self.comboRecipientActive.currentText()
        # Get message from input box
        message = self.inputMessageActive.toPlainText()
        # Clear input box
        self.inputMessageActive.clear()
        # Add message to chat display
        self.displayMessageActive.append(
            f"{self.inputNickLog.text()}: {message}........('Sent to {recipient}')"
        )

    def switch_reset(self):
        # go to the reset tab
        self.authTabs.setCurrentIndex(2)

    def go_to_archive(self):
        # go to the archives window
        self.stackedWidget.setCurrentIndex(3)

    def go_to_active_chat(self):
        # go to the archives window
        self.stackedWidget.setCurrentIndex(2)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
